// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Rooby.Api.Data;

#nullable disable

namespace Rooby.Api.Data.Migrations
{
    [DbContext(typeof(RoobyDbContext))]
    partial class RoobyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rooby.Api.Data.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.HasKey("Id", "VersionId")
                        .HasName("pk_item");

                    b.HasIndex("ProfileId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_item_profile_id_key_draft")
                        .HasFilter("version_id = -1");

                    b.HasIndex("ProfileId", "VersionId")
                        .HasDatabaseName("ix_item_profile_id_version_id");

                    b.HasIndex("ProfileId", "Key", "VersionId")
                        .HasDatabaseName("ix_item_profile_id_key_version_id");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.ItemLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<bool>("InheritSchema")
                        .HasColumnType("boolean")
                        .HasColumnName("inherit_schema");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<NpgsqlRange<DateOnly>?>("Validity")
                        .HasColumnType("daterange")
                        .HasColumnName("validity");

                    b.HasKey("Id", "VersionId")
                        .HasName("pk_item_line");

                    b.HasIndex("ProfileId", "VersionId")
                        .HasDatabaseName("ix_item_line_profile_id_version_id");

                    b.HasIndex("ProfileId", "ItemId", "VersionId")
                        .HasDatabaseName("ix_item_line_profile_id_item_id_version_id");

                    b.ToTable("item_line", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NextStashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-2)
                        .HasColumnName("next_stash_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PublishSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publish_secret");

                    b.Property<string>("PublishUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publish_uri");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remark");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TestGate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("test_gate");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_project_id_code");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remark");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_project_code");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Schema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<NpgsqlRange<DateOnly>>("Validity")
                        .HasColumnType("daterange")
                        .HasColumnName("validity");

                    b.HasKey("Id")
                        .HasName("pk_schema");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_schema_project_id");

                    b.ToTable("schema", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.Property<JsonDocument>("InputData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("item_key");

                    b.Property<JsonDocument>("OutputValue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_value");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remarks");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id", "VersionId")
                        .HasName("pk_test_case");

                    b.HasIndex("ProfileId", "ItemKey")
                        .HasDatabaseName("ix_test_case_profile_id_item_key");

                    b.HasIndex("ProfileId", "VersionId")
                        .HasDatabaseName("ix_test_case_profile_id_version_id");

                    b.ToTable("test_case", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login_name");

                    b.Property<int>("LoginProvider")
                        .HasColumnType("integer")
                        .HasColumnName("login_provider");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_access");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_access_user_id");

                    b.ToTable("user_access", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_access_scope", "project_id IS NOT NULL OR profile_id IS NULL");
                        });
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<int>("FromVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("from_version_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_version");

                    b.HasAlternateKey("ProfileId", "VersionId")
                        .HasName("ak_versions_profile_id_version_id");

                    b.HasIndex("ProfileId", "VersionId")
                        .IsUnique()
                        .HasDatabaseName("ix_version_profile_id_version_id");

                    b.ToTable("version", null, t =>
                        {
                            t.HasCheckConstraint("ck_version_ids", "version_id <> 0 AND from_version_id >= 0");
                        });
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.VersionSchema", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.Property<Guid>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.Property<JsonDocument>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<NpgsqlRange<DateOnly>>("Validity")
                        .HasColumnType("daterange")
                        .HasColumnName("validity");

                    b.HasKey("ProfileId", "VersionId", "SchemaId")
                        .HasName("pk_version_schema");

                    b.ToTable("version_schema", (string)null);
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Item", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Version", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "VersionId")
                        .HasPrincipalKey("ProfileId", "VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_versions_profile_id_version_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("ItemId", "ItemVersionId");

                            b1.ToTable("item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId", "ItemVersionId")
                                .HasConstraintName("fk_item_item_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Deleted", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("deleted_by_user_id");

                            b1.HasKey("ItemId", "ItemVersionId");

                            b1.ToTable("item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId", "ItemVersionId")
                                .HasConstraintName("fk_item_item_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("ItemId", "ItemVersionId");

                            b1.ToTable("item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId", "ItemVersionId")
                                .HasConstraintName("fk_item_item_id_version_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Deleted");

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.ItemLine", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Version", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "VersionId")
                        .HasPrincipalKey("ProfileId", "VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_line_versions_profile_id_version_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("ItemLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemLineVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("ItemLineId", "ItemLineVersionId");

                            b1.ToTable("item_line");

                            b1.WithOwner()
                                .HasForeignKey("ItemLineId", "ItemLineVersionId")
                                .HasConstraintName("fk_item_line_item_line_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Deleted", b1 =>
                        {
                            b1.Property<Guid>("ItemLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemLineVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("deleted_by_user_id");

                            b1.HasKey("ItemLineId", "ItemLineVersionId");

                            b1.ToTable("item_line");

                            b1.WithOwner()
                                .HasForeignKey("ItemLineId", "ItemLineVersionId")
                                .HasConstraintName("fk_item_line_item_line_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("ItemLineId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ItemLineVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("ItemLineId", "ItemLineVersionId");

                            b1.ToTable("item_line");

                            b1.WithOwner()
                                .HasForeignKey("ItemLineId", "ItemLineVersionId")
                                .HasConstraintName("fk_item_line_item_line_id_version_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Deleted");

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Profile", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Project", "Project")
                        .WithMany("Profiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_projects_project_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "ApiKeyRotated", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("api_key_rotated_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("api_key_rotated_by_user_id");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId")
                                .HasConstraintName("fk_profile_profile_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId")
                                .HasConstraintName("fk_profile_profile_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId")
                                .HasConstraintName("fk_profile_profile_id");
                        });

                    b.Navigation("ApiKeyRotated");

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("LastModified");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Project", b =>
                {
                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("ProjectId");

                            b1.ToTable("project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_project_project_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("ProjectId");

                            b1.ToTable("project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_project_project_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Schema", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Project", null)
                        .WithMany("Schemas")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schema_project_project_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("SchemaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("SchemaId");

                            b1.ToTable("schema");

                            b1.WithOwner()
                                .HasForeignKey("SchemaId")
                                .HasConstraintName("fk_schema_schema_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("SchemaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("SchemaId");

                            b1.ToTable("schema");

                            b1.WithOwner()
                                .HasForeignKey("SchemaId")
                                .HasConstraintName("fk_schema_schema_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.TestCase", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Version", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "VersionId")
                        .HasPrincipalKey("ProfileId", "VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_versions_profile_id_version_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<Guid>("TestCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("TestCaseVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("TestCaseId", "TestCaseVersionId");

                            b1.ToTable("test_case");

                            b1.WithOwner()
                                .HasForeignKey("TestCaseId", "TestCaseVersionId")
                                .HasConstraintName("fk_test_case_test_case_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Deleted", b1 =>
                        {
                            b1.Property<Guid>("TestCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("TestCaseVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("deleted_by_user_id");

                            b1.HasKey("TestCaseId", "TestCaseVersionId");

                            b1.ToTable("test_case");

                            b1.WithOwner()
                                .HasForeignKey("TestCaseId", "TestCaseVersionId")
                                .HasConstraintName("fk_test_case_test_case_id_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<Guid>("TestCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("TestCaseVersionId")
                                .HasColumnType("integer")
                                .HasColumnName("version_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("TestCaseId", "TestCaseVersionId");

                            b1.ToTable("test_case");

                            b1.WithOwner()
                                .HasForeignKey("TestCaseId", "TestCaseVersionId")
                                .HasConstraintName("fk_test_case_test_case_id_version_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Deleted");

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.User", b =>
                {
                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("LastModified");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.UserAccess", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_access_users_user_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<int>("UserAccessId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("UserAccessId");

                            b1.ToTable("user_access");

                            b1.WithOwner()
                                .HasForeignKey("UserAccessId")
                                .HasConstraintName("fk_user_access_user_access_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "LastModified", b1 =>
                        {
                            b1.Property<int>("UserAccessId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_modified_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("last_modified_by_user_id");

                            b1.HasKey("UserAccessId");

                            b1.ToTable("user_access");

                            b1.WithOwner()
                                .HasForeignKey("UserAccessId")
                                .HasConstraintName("fk_user_access_user_access_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Revoked", b1 =>
                        {
                            b1.Property<int>("UserAccessId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("revoked_by_user_id");

                            b1.HasKey("UserAccessId");

                            b1.ToTable("user_access");

                            b1.WithOwner()
                                .HasForeignKey("UserAccessId")
                                .HasConstraintName("fk_user_access_user_access_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("LastModified");

                    b.Navigation("Revoked");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Version", b =>
                {
                    b.HasOne("Rooby.Api.Data.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_version_profile_profile_id");

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Created", b1 =>
                        {
                            b1.Property<int>("VersionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("created_by_user_id");

                            b1.HasKey("VersionId");

                            b1.ToTable("version");

                            b1.WithOwner()
                                .HasForeignKey("VersionId")
                                .HasConstraintName("fk_version_version_id");
                        });

                    b.OwnsOne("Rooby.Api.Data.Entities.UserLog", "Published", b1 =>
                        {
                            b1.Property<int>("VersionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<int>("ByUserId")
                                .HasColumnType("integer")
                                .HasColumnName("published_by_user_id");

                            b1.HasKey("VersionId");

                            b1.ToTable("version");

                            b1.WithOwner()
                                .HasForeignKey("VersionId")
                                .HasConstraintName("fk_version_version_id");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Published");
                });

            modelBuilder.Entity("Rooby.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Schemas");
                });
#pragma warning restore 612, 618
        }
    }
}
